spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adsDB
    username: student
    password: chocolatefrog
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yml